// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzBasket = "tz_basket"

// TzBasket 购物车
type TzBasket struct {
	BasketID           uint64    `gorm:"column:basket_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"basket_id"`                                   // 主键
	ShopID             int64     `gorm:"column:shop_id;type:bigint(20);not null;uniqueIndex:uk_user_shop_sku,priority:3;index:shop_id,priority:1;comment:店铺ID" json:"shop_id"`  // 店铺ID
	ProdID             uint64    `gorm:"column:prod_id;type:bigint(20) unsigned;not null;comment:产品ID" json:"prod_id"`                                                          // 产品ID
	SkuID              uint64    `gorm:"column:sku_id;type:bigint(20) unsigned;not null;uniqueIndex:uk_user_shop_sku,priority:1;comment:SkuID" json:"sku_id"`                   // SkuID
	UserID             string    `gorm:"column:user_id;type:varchar(50);not null;uniqueIndex:uk_user_shop_sku,priority:2;index:user_id,priority:1;comment:用户ID" json:"user_id"` // 用户ID
	BasketCount        int32     `gorm:"column:basket_count;type:int(11);not null;comment:购物车产品个数" json:"basket_count"`                                                         // 购物车产品个数
	BasketDate         time.Time `gorm:"column:basket_date;type:datetime;not null;comment:购物时间" json:"basket_date"`                                                             // 购物时间
	DiscountID         *int64    `gorm:"column:discount_id;type:bigint(20);comment:满减活动ID" json:"discount_id"`                                                                  // 满减活动ID
	DistributionCardNo *string   `gorm:"column:distribution_card_no;type:varchar(36);comment:分销推广人卡号" json:"distribution_card_no"`                                              // 分销推广人卡号
}

// TableName TzBasket's table name
func (*TzBasket) TableName() string {
	return TableNameTzBasket
}
