// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzCategoryProp = "tz_category_prop"

// TzCategoryProp mapped from table <tz_category_prop>
type TzCategoryProp struct {
	ID         int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CategoryID *int64 `gorm:"column:category_id;type:bigint(20);index:category_id,priority:1;comment:分类id" json:"category_id"`              // 分类id
	PropID     *int64 `gorm:"column:prop_id;type:bigint(20);index:prop_id,priority:1;comment:商品属性id即表tz_prod_prop中的prop_id" json:"prop_id"` // 商品属性id即表tz_prod_prop中的prop_id
}

// TableName TzCategoryProp's table name
func (*TzCategoryProp) TableName() string {
	return TableNameTzCategoryProp
}
