// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzCategoryBrand = "tz_category_brand"

// TzCategoryBrand mapped from table <tz_category_brand>
type TzCategoryBrand struct {
	ID         int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CategoryID *int64 `gorm:"column:category_id;type:bigint(20);index:category_id,priority:1;comment:分类id" json:"category_id"` // 分类id
	BrandID    *int64 `gorm:"column:brand_id;type:bigint(20);index:brand_id,priority:1;comment:品牌id" json:"brand_id"`          // 品牌id
}

// TableName TzCategoryBrand's table name
func (*TzCategoryBrand) TableName() string {
	return TableNameTzCategoryBrand
}
