// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzDelivery = "tz_delivery"

// TzDelivery 物流公司
type TzDelivery struct {
	DvyID          uint64    `gorm:"column:dvy_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"dvy_id"` // ID
	DvyName        string    `gorm:"column:dvy_name;type:varchar(50);not null;comment:物流公司名称" json:"dvy_name"`                      // 物流公司名称
	CompanyHomeURL *string   `gorm:"column:company_home_url;type:varchar(255);comment:公司主页" json:"company_home_url"`                // 公司主页
	RecTime        time.Time `gorm:"column:rec_time;type:datetime;not null;comment:建立时间" json:"rec_time"`                           // 建立时间
	ModifyTime     time.Time `gorm:"column:modify_time;type:datetime;not null;comment:修改时间" json:"modify_time"`                     // 修改时间
	QueryURL       string    `gorm:"column:query_url;type:varchar(520);not null;comment:物流查询接口" json:"query_url"`                   // 物流查询接口
}

// TableName TzDelivery's table name
func (*TzDelivery) TableName() string {
	return TableNameTzDelivery
}
