// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzHotSearch = "tz_hot_search"

// TzHotSearch 热搜
type TzHotSearch struct {
	HotSearchID uint64    `gorm:"column:hot_search_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"hot_search_id"` // 主键
	ShopID      *int64    `gorm:"column:shop_id;type:bigint(20);index:shop_id,priority:1;comment:店铺ID 0为全局热搜" json:"shop_id"`                  // 店铺ID 0为全局热搜
	Content     string    `gorm:"column:content;type:varchar(255);not null;comment:内容" json:"content"`                                         // 内容
	RecDate     time.Time `gorm:"column:rec_date;type:datetime;not null;comment:录入时间" json:"rec_date"`                                         // 录入时间
	Seq         *int32    `gorm:"column:seq;type:int(11);comment:顺序" json:"seq"`                                                               // 顺序
	Status      *int32    `gorm:"column:status;type:tinyint(2);not null;default:1;comment:状态 0下线 1上线" json:"status"`                           // 状态 0下线 1上线
	Title       string    `gorm:"column:title;type:varchar(255);not null;comment:热搜标题" json:"title"`                                           // 热搜标题
}

// TableName TzHotSearch's table name
func (*TzHotSearch) TableName() string {
	return TableNameTzHotSearch
}
