// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzIndexImg = "tz_index_img"

// TzIndexImg 主页轮播图
type TzIndexImg struct {
	ImgID      uint64     `gorm:"column:img_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"img_id"` // 主键
	ShopID     *int64     `gorm:"column:shop_id;type:bigint(20);index:shop_id,priority:1;comment:店铺ID" json:"shop_id"`           // 店铺ID
	ImgURL     string     `gorm:"column:img_url;type:varchar(200);not null;comment:图片" json:"img_url"`                           // 图片
	Des        *string    `gorm:"column:des;type:varchar(200);comment:说明文字,描述" json:"des"`                                       // 说明文字,描述
	Title      *string    `gorm:"column:title;type:varchar(200);comment:标题" json:"title"`                                        // 标题
	Link       *string    `gorm:"column:link;type:varchar(200);comment:链接" json:"link"`                                          // 链接
	Status     *bool      `gorm:"column:status;type:tinyint(1);comment:状态" json:"status"`                                        // 状态
	Seq        *int32     `gorm:"column:seq;type:int(11);comment:顺序" json:"seq"`                                                 // 顺序
	UploadTime *time.Time `gorm:"column:upload_time;type:datetime;comment:上传时间" json:"upload_time"`                              // 上传时间
	Relation   *int64     `gorm:"column:relation;type:bigint(20);comment:关联" json:"relation"`                                    // 关联
	Type       *int32     `gorm:"column:type;type:int(2);comment:类型" json:"type"`                                                // 类型
}

// TableName TzIndexImg's table name
func (*TzIndexImg) TableName() string {
	return TableNameTzIndexImg
}
