// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzMessage = "tz_message"

// TzMessage mapped from table <tz_message>
type TzMessage struct {
	ID         uint64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;comment:留言创建时间" json:"create_time"` // 留言创建时间
	UserName   *string    `gorm:"column:user_name;type:varchar(36);comment:姓名" json:"user_name"`      // 姓名
	Email      *string    `gorm:"column:email;type:varchar(64);comment:邮箱" json:"email"`              // 邮箱
	Contact    *string    `gorm:"column:contact;type:varchar(36);comment:联系方式" json:"contact"`        // 联系方式
	Content    *string    `gorm:"column:content;type:text;comment:留言内容" json:"content"`               // 留言内容
	Reply      *string    `gorm:"column:reply;type:text;comment:留言回复" json:"reply"`                   // 留言回复
	Status     *int32     `gorm:"column:status;type:tinyint(2);comment:状态：0:未审核 1审核通过" json:"status"` // 状态：0:未审核 1审核通过
}

// TableName TzMessage's table name
func (*TzMessage) TableName() string {
	return TableNameTzMessage
}
