// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzNotice = "tz_notice"

// TzNotice mapped from table <tz_notice>
type TzNotice struct {
	ID          int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:公告id" json:"id"`              // 公告id
	ShopID      *int64     `gorm:"column:shop_id;type:bigint(20);comment:店铺id" json:"shop_id"`                                  // 店铺id
	Title       *string    `gorm:"column:title;type:varchar(36);comment:公告标题" json:"title"`                                     // 公告标题
	Content     *string    `gorm:"column:content;type:text;comment:公告内容" json:"content"`                                        // 公告内容
	Status      *bool      `gorm:"column:status;type:tinyint(1);comment:状态(1:公布 0:撤回)" json:"status"`                           // 状态(1:公布 0:撤回)
	IsTop       *int32     `gorm:"column:is_top;type:tinyint(2);comment:是否置顶" json:"is_top"`                                    // 是否置顶
	PublishTime *time.Time `gorm:"column:publish_time;type:timestamp;comment:发布时间" json:"publish_time"`                         // 发布时间
	UpdateTime  *time.Time `gorm:"column:update_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName TzNotice's table name
func (*TzNotice) TableName() string {
	return TableNameTzNotice
}
