// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzOrderItem = "tz_order_item"

// TzOrderItem 订单项
type TzOrderItem struct {
	OrderItemID        uint64     `gorm:"column:order_item_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:订单项ID" json:"order_item_id"`         // 订单项ID
	ShopID             int64      `gorm:"column:shop_id;type:bigint(20);not null;comment:店铺id" json:"shop_id"`                                                    // 店铺id
	OrderNumber        string     `gorm:"column:order_number;type:varchar(50);not null;index:order_number,priority:1;comment:订单order_number" json:"order_number"` // 订单order_number
	ProdID             uint64     `gorm:"column:prod_id;type:bigint(20) unsigned;not null;comment:产品ID" json:"prod_id"`                                           // 产品ID
	SkuID              uint64     `gorm:"column:sku_id;type:bigint(20) unsigned;not null;comment:产品SkuID" json:"sku_id"`                                          // 产品SkuID
	ProdCount          int32      `gorm:"column:prod_count;type:int(11);not null;comment:购物车产品个数" json:"prod_count"`                                              // 购物车产品个数
	ProdName           string     `gorm:"column:prod_name;type:varchar(120);not null;comment:产品名称" json:"prod_name"`                                              // 产品名称
	SkuName            *string    `gorm:"column:sku_name;type:varchar(120);comment:sku名称" json:"sku_name"`                                                        // sku名称
	Pic                string     `gorm:"column:pic;type:varchar(255);not null;comment:产品主图片路径" json:"pic"`                                                       // 产品主图片路径
	Price              float64    `gorm:"column:price;type:decimal(15,2);not null;comment:产品价格" json:"price"`                                                     // 产品价格
	UserID             string     `gorm:"column:user_id;type:varchar(36);not null;comment:用户Id" json:"user_id"`                                                   // 用户Id
	ProductTotalAmount float64    `gorm:"column:product_total_amount;type:decimal(15,2);not null;comment:商品总金额" json:"product_total_amount"`                      // 商品总金额
	RecTime            time.Time  `gorm:"column:rec_time;type:datetime;not null;comment:购物时间" json:"rec_time"`                                                    // 购物时间
	CommSts            int32      `gorm:"column:comm_sts;type:int(1);not null;comment:评论状态： 0 未评价  1 已评价" json:"comm_sts"`                                        // 评论状态： 0 未评价  1 已评价
	DistributionCardNo *string    `gorm:"column:distribution_card_no;type:varchar(36);comment:推广员使用的推销卡号" json:"distribution_card_no"`                            // 推广员使用的推销卡号
	BasketDate         *time.Time `gorm:"column:basket_date;type:datetime;comment:加入购物车时间" json:"basket_date"`                                                    // 加入购物车时间
}

// TableName TzOrderItem's table name
func (*TzOrderItem) TableName() string {
	return TableNameTzOrderItem
}
