// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzOrderRefund = "tz_order_refund"

// TzOrderRefund mapped from table <tz_order_refund>
type TzOrderRefund struct {
	RefundID       int64      `gorm:"column:refund_id;type:bigint(20);primaryKey;autoIncrement:true;comment:记录ID" json:"refund_id"`                     // 记录ID
	ShopID         int64      `gorm:"column:shop_id;type:bigint(20);not null;comment:店铺ID" json:"shop_id"`                                              // 店铺ID
	OrderID        int64      `gorm:"column:order_id;type:bigint(20);not null;comment:订单ID" json:"order_id"`                                            // 订单ID
	OrderNumber    string     `gorm:"column:order_number;type:varchar(50);not null;index:order_number,priority:1;comment:订单流水号" json:"order_number"`    // 订单流水号
	OrderAmount    float64    `gorm:"column:order_amount;type:double(12,2);not null;comment:订单总金额" json:"order_amount"`                                 // 订单总金额
	OrderItemID    int64      `gorm:"column:order_item_id;type:bigint(20);not null;comment:订单项ID 全部退款是0" json:"order_item_id"`                          // 订单项ID 全部退款是0
	RefundSn       string     `gorm:"column:refund_sn;type:varchar(50);not null;uniqueIndex:refund_sn_unique,priority:1;comment:退款编号" json:"refund_sn"` // 退款编号
	FlowTradeNo    string     `gorm:"column:flow_trade_no;type:varchar(100);not null;comment:订单支付流水号" json:"flow_trade_no"`                             // 订单支付流水号
	OutRefundNo    *string    `gorm:"column:out_refund_no;type:varchar(200);comment:第三方退款单号(微信退款单号)" json:"out_refund_no"`                              // 第三方退款单号(微信退款单号)
	PayType        *int32     `gorm:"column:pay_type;type:int(1);comment:订单支付方式 1 微信支付 2 支付宝" json:"pay_type"`                                          // 订单支付方式 1 微信支付 2 支付宝
	PayTypeName    *string    `gorm:"column:pay_type_name;type:varchar(50);comment:订单支付名称" json:"pay_type_name"`                                        // 订单支付名称
	UserID         string     `gorm:"column:user_id;type:varchar(50);not null;comment:买家ID" json:"user_id"`                                             // 买家ID
	GoodsNum       *int32     `gorm:"column:goods_num;type:int(11);comment:退货数量" json:"goods_num"`                                                      // 退货数量
	RefundAmount   float64    `gorm:"column:refund_amount;type:decimal(10,2);not null;comment:退款金额" json:"refund_amount"`                               // 退款金额
	ApplyType      int32      `gorm:"column:apply_type;type:int(1);not null;comment:申请类型:1,仅退款,2退款退货" json:"apply_type"`                                // 申请类型:1,仅退款,2退款退货
	RefundSts      int32      `gorm:"column:refund_sts;type:int(1);not null;comment:处理状态:1为待审核,2为同意,3为不同意" json:"refund_sts"`                           // 处理状态:1为待审核,2为同意,3为不同意
	ReturnMoneySts int32      `gorm:"column:return_money_sts;type:int(1);not null;comment:处理退款状态: 0:退款处理中 1:退款成功 -1:退款失败" json:"return_money_sts"`      // 处理退款状态: 0:退款处理中 1:退款成功 -1:退款失败
	ApplyTime      time.Time  `gorm:"column:apply_time;type:datetime;not null;comment:申请时间" json:"apply_time"`                                          // 申请时间
	HandelTime     *time.Time `gorm:"column:handel_time;type:datetime;comment:卖家处理时间" json:"handel_time"`                                               // 卖家处理时间
	RefundTime     *time.Time `gorm:"column:refund_time;type:datetime;comment:退款时间" json:"refund_time"`                                                 // 退款时间
	PhotoFiles     *string    `gorm:"column:photo_files;type:varchar(150);comment:文件凭证json" json:"photo_files"`                                         // 文件凭证json
	BuyerMsg       *string    `gorm:"column:buyer_msg;type:varchar(300);comment:申请原因" json:"buyer_msg"`                                                 // 申请原因
	SellerMsg      *string    `gorm:"column:seller_msg;type:varchar(300);comment:卖家备注" json:"seller_msg"`                                               // 卖家备注
	ExpressName    *string    `gorm:"column:express_name;type:varchar(50);comment:物流公司名称" json:"express_name"`                                          // 物流公司名称
	ExpressNo      *string    `gorm:"column:express_no;type:varchar(50);comment:物流单号" json:"express_no"`                                                // 物流单号
	ShipTime       *time.Time `gorm:"column:ship_time;type:datetime;comment:发货时间" json:"ship_time"`                                                     // 发货时间
	ReceiveTime    *time.Time `gorm:"column:receive_time;type:datetime;comment:收货时间" json:"receive_time"`                                               // 收货时间
	ReceiveMessage *string    `gorm:"column:receive_message;type:varchar(300);comment:收货备注" json:"receive_message"`                                     // 收货备注
}

// TableName TzOrderRefund's table name
func (*TzOrderRefund) TableName() string {
	return TableNameTzOrderRefund
}
