// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzProdProp = "tz_prod_prop"

// TzProdProp mapped from table <tz_prod_prop>
type TzProdProp struct {
	PropID   int64   `gorm:"column:prop_id;type:bigint(20);primaryKey;autoIncrement:true;comment:属性id" json:"prop_id"` // 属性id
	PropName *string `gorm:"column:prop_name;type:varchar(20);comment:属性名称" json:"prop_name"`                          // 属性名称
	Rule     *int32  `gorm:"column:rule;type:tinyint(2);comment:ProdPropRule 1:销售属性(规格); 2:参数属性;" json:"rule"`         // ProdPropRule 1:销售属性(规格); 2:参数属性;
	ShopID   *int64  `gorm:"column:shop_id;type:bigint(20);index:shop_id,priority:1;comment:店铺id" json:"shop_id"`      // 店铺id
}

// TableName TzProdProp's table name
func (*TzProdProp) TableName() string {
	return TableNameTzProdProp
}
