// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzProdTagReference = "tz_prod_tag_reference"

// TzProdTagReference mapped from table <tz_prod_tag_reference>
type TzProdTagReference struct {
	ReferenceID int64      `gorm:"column:reference_id;type:bigint(20);primaryKey;autoIncrement:true;comment:分组引用id" json:"reference_id"` // 分组引用id
	ShopID      *int64     `gorm:"column:shop_id;type:bigint(20);comment:店铺id" json:"shop_id"`                                           // 店铺id
	TagID       *int64     `gorm:"column:tag_id;type:bigint(20);comment:标签id" json:"tag_id"`                                             // 标签id
	ProdID      *int64     `gorm:"column:prod_id;type:bigint(20);comment:商品id" json:"prod_id"`                                           // 商品id
	Status      *bool      `gorm:"column:status;type:tinyint(1);comment:状态(1:正常,0:删除)" json:"status"`                                    // 状态(1:正常,0:删除)
	CreateTime  *time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName TzProdTagReference's table name
func (*TzProdTagReference) TableName() string {
	return TableNameTzProdTagReference
}
