// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzProdPropValue = "tz_prod_prop_value"

// TzProdPropValue mapped from table <tz_prod_prop_value>
type TzProdPropValue struct {
	ValueID   int64   `gorm:"column:value_id;type:bigint(20);primaryKey;autoIncrement:true;comment:属性值ID" json:"value_id"` // 属性值ID
	PropValue *string `gorm:"column:prop_value;type:varchar(20);comment:属性值名称" json:"prop_value"`                          // 属性值名称
	PropID    *int64  `gorm:"column:prop_id;type:bigint(20);index:prop_id,priority:1;comment:属性ID" json:"prop_id"`         // 属性ID
}

// TableName TzProdPropValue's table name
func (*TzProdPropValue) TableName() string {
	return TableNameTzProdPropValue
}
