// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzPickAddr = "tz_pick_addr"

// TzPickAddr 用户配送地址
type TzPickAddr struct {
	AddrID     uint64  `gorm:"column:addr_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"addr_id"` // ID
	AddrName   *string `gorm:"column:addr_name;type:varchar(36);comment:自提点名称" json:"addr_name"`                                // 自提点名称
	Addr       *string `gorm:"column:addr;type:varchar(1000);comment:地址" json:"addr"`                                           // 地址
	Mobile     *string `gorm:"column:mobile;type:varchar(20);comment:手机" json:"mobile"`                                         // 手机
	ProvinceID *int64  `gorm:"column:province_id;type:bigint(20);comment:省份ID" json:"province_id"`                              // 省份ID
	Province   *string `gorm:"column:province;type:varchar(32);comment:省份" json:"province"`                                     // 省份
	CityID     *int64  `gorm:"column:city_id;type:bigint(20);comment:城市ID" json:"city_id"`                                      // 城市ID
	City       *string `gorm:"column:city;type:varchar(32);comment:城市" json:"city"`                                             // 城市
	AreaID     *int64  `gorm:"column:area_id;type:bigint(20);comment:区/县ID" json:"area_id"`                                     // 区/县ID
	Area       *string `gorm:"column:area;type:varchar(32);comment:区/县" json:"area"`                                            // 区/县
	ShopID     *int64  `gorm:"column:shop_id;type:bigint(20);comment:店铺id" json:"shop_id"`                                      // 店铺id
}

// TableName TzPickAddr's table name
func (*TzPickAddr) TableName() string {
	return TableNameTzPickAddr
}
