// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzProdTag = "tz_prod_tag"

// TzProdTag 商品分组表
type TzProdTag struct {
	ID         int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:分组标签id" json:"id"` // 分组标签id
	Title      *string    `gorm:"column:title;type:varchar(36);comment:分组标题" json:"title"`                          // 分组标题
	ShopID     *int64     `gorm:"column:shop_id;type:bigint(20);comment:店铺Id" json:"shop_id"`                       // 店铺Id
	Status     *bool      `gorm:"column:status;type:tinyint(1);comment:状态(1为正常,0为删除)" json:"status"`                // 状态(1为正常,0为删除)
	IsDefault  *bool      `gorm:"column:is_default;type:tinyint(1);comment:默认类型(0:商家自定义,1:系统默认)" json:"is_default"` // 默认类型(0:商家自定义,1:系统默认)
	ProdCount  *int64     `gorm:"column:prod_count;type:bigint(20);comment:商品数量" json:"prod_count"`                 // 商品数量
	Style      *int32     `gorm:"column:style;type:int(10);comment:列表样式(0:一列一个,1:一列两个,2:一列三个)" json:"style"`        // 列表样式(0:一列一个,1:一列两个,2:一列三个)
	Seq        *int32     `gorm:"column:seq;type:int(10);comment:排序" json:"seq"`                                    // 排序
	CreateTime *time.Time `gorm:"column:create_time;type:timestamp;comment:创建时间" json:"create_time"`                // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;type:timestamp;comment:修改时间" json:"update_time"`                // 修改时间
	DeleteTime *time.Time `gorm:"column:delete_time;type:timestamp;comment:删除时间" json:"delete_time"`                // 删除时间
}

// TableName TzProdTag's table name
func (*TzProdTag) TableName() string {
	return TableNameTzProdTag
}
