// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzProdFavorite = "tz_prod_favorite"

// TzProdFavorite 商品收藏表
type TzProdFavorite struct {
	FavoriteID uint64    `gorm:"column:favorite_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键" json:"favorite_id"` // 主键
	ProdID     uint64    `gorm:"column:prod_id;type:bigint(20) unsigned;not null;index:prod_id,priority:1;comment:商品ID" json:"prod_id"`   // 商品ID
	RecTime    time.Time `gorm:"column:rec_time;type:datetime;not null;comment:收藏时间" json:"rec_time"`                                     // 收藏时间
	UserID     string    `gorm:"column:user_id;type:varchar(36);not null;comment:用户ID" json:"user_id"`                                    // 用户ID
}

// TableName TzProdFavorite's table name
func (*TzProdFavorite) TableName() string {
	return TableNameTzProdFavorite
}
