// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzSysRoleMenu = "tz_sys_role_menu"

// TzSysRoleMenu 角色与菜单对应关系
type TzSysRoleMenu struct {
	ID     int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	RoleID *int64 `gorm:"column:role_id;type:bigint(20);comment:角色ID" json:"role_id"` // 角色ID
	MenuID *int64 `gorm:"column:menu_id;type:bigint(20);comment:菜单ID" json:"menu_id"` // 菜单ID
}

// TableName TzSysRoleMenu's table name
func (*TzSysRoleMenu) TableName() string {
	return TableNameTzSysRoleMenu
}
