// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzSysRole = "tz_sys_role"

// TzSysRole 角色
type TzSysRole struct {
	RoleID       int64      `gorm:"column:role_id;type:bigint(20);primaryKey;autoIncrement:true" json:"role_id"`
	RoleName     *string    `gorm:"column:role_name;type:varchar(100);comment:角色名称" json:"role_name"`          // 角色名称
	Remark       *string    `gorm:"column:remark;type:varchar(100);comment:备注" json:"remark"`                  // 备注
	CreateUserID *int64     `gorm:"column:create_user_id;type:bigint(20);comment:创建者ID" json:"create_user_id"` // 创建者ID
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`          // 创建时间
}

// TableName TzSysRole's table name
func (*TzSysRole) TableName() string {
	return TableNameTzSysRole
}
