// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzSysConfig = "tz_sys_config"

// TzSysConfig 系统配置信息表
type TzSysConfig struct {
	ID         int64   `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	ParamKey   *string `gorm:"column:param_key;type:varchar(50);uniqueIndex:key,priority:1;comment:key" json:"param_key"` // key
	ParamValue *string `gorm:"column:param_value;type:varchar(2000);comment:value" json:"param_value"`                    // value
	Remark     *string `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`                                  // 备注
}

// TableName TzSysConfig's table name
func (*TzSysConfig) TableName() string {
	return TableNameTzSysConfig
}
