// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzSysMenu = "tz_sys_menu"

// TzSysMenu 菜单管理
type TzSysMenu struct {
	MenuID   int64   `gorm:"column:menu_id;type:bigint(20);primaryKey;autoIncrement:true" json:"menu_id"`
	ParentID *int64  `gorm:"column:parent_id;type:bigint(20);comment:父菜单ID，一级菜单为0" json:"parent_id"`                  // 父菜单ID，一级菜单为0
	Name     *string `gorm:"column:name;type:varchar(50);comment:菜单名称" json:"name"`                                   // 菜单名称
	URL      *string `gorm:"column:url;type:varchar(200);comment:菜单URL" json:"url"`                                   // 菜单URL
	Perms    *string `gorm:"column:perms;type:varchar(500);comment:授权(多个用逗号分隔，如：user:list,user:create)" json:"perms"` // 授权(多个用逗号分隔，如：user:list,user:create)
	Type     *int32  `gorm:"column:type;type:int(11);comment:类型   0：目录   1：菜单   2：按钮" json:"type"`                    // 类型   0：目录   1：菜单   2：按钮
	Icon     *string `gorm:"column:icon;type:varchar(50);comment:菜单图标" json:"icon"`                                   // 菜单图标
	OrderNum *int32  `gorm:"column:order_num;type:int(11);comment:排序" json:"order_num"`                               // 排序
}

// TableName TzSysMenu's table name
func (*TzSysMenu) TableName() string {
	return TableNameTzSysMenu
}
