// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzSysLog = "tz_sys_log"

// TzSysLog 系统日志
type TzSysLog struct {
	ID         int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	Username   *string    `gorm:"column:username;type:varchar(50);comment:用户名" json:"username"`      // 用户名
	Operation  *string    `gorm:"column:operation;type:varchar(50);comment:用户操作" json:"operation"`   // 用户操作
	Method     *string    `gorm:"column:method;type:varchar(200);comment:请求方法" json:"method"`        // 请求方法
	Params     *string    `gorm:"column:params;type:varchar(5000);comment:请求参数" json:"params"`       // 请求参数
	Time       int64      `gorm:"column:time;type:bigint(20);not null;comment:执行时长(毫秒)" json:"time"` // 执行时长(毫秒)
	IP         *string    `gorm:"column:ip;type:varchar(64);comment:IP地址" json:"ip"`                 // IP地址
	CreateDate *time.Time `gorm:"column:create_date;type:datetime;comment:创建时间" json:"create_date"`  // 创建时间
}

// TableName TzSysLog's table name
func (*TzSysLog) TableName() string {
	return TableNameTzSysLog
}
