// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzSysUserRole = "tz_sys_user_role"

// TzSysUserRole 用户与角色对应关系
type TzSysUserRole struct {
	ID     int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	UserID *int64 `gorm:"column:user_id;type:bigint(20);comment:用户ID" json:"user_id"` // 用户ID
	RoleID *int64 `gorm:"column:role_id;type:bigint(20);comment:角色ID" json:"role_id"` // 角色ID
}

// TableName TzSysUserRole's table name
func (*TzSysUserRole) TableName() string {
	return TableNameTzSysUserRole
}
