// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzSysUser = "tz_sys_user"

// TzSysUser 系统用户
type TzSysUser struct {
	UserID       int64      `gorm:"column:user_id;type:bigint(20);primaryKey;autoIncrement:true" json:"user_id"`
	Username     string     `gorm:"column:username;type:varchar(50);not null;uniqueIndex:username,priority:1;comment:用户名" json:"username"` // 用户名
	Password     *string    `gorm:"column:password;type:varchar(100);comment:密码" json:"password"`                                          // 密码
	Email        *string    `gorm:"column:email;type:varchar(100);comment:邮箱" json:"email"`                                                // 邮箱
	Mobile       *string    `gorm:"column:mobile;type:varchar(100);comment:手机号" json:"mobile"`                                             // 手机号
	Status       *int32     `gorm:"column:status;type:tinyint(4);comment:状态  0：禁用   1：正常" json:"status"`                                   // 状态  0：禁用   1：正常
	CreateUserID *int64     `gorm:"column:create_user_id;type:bigint(20);comment:创建者ID" json:"create_user_id"`                             // 创建者ID
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`                                      // 创建时间
	ShopID       *int64     `gorm:"column:shop_id;type:bigint(20);comment:用户所在的商城Id" json:"shop_id"`                                       // 用户所在的商城Id
}

// TableName TzSysUser's table name
func (*TzSysUser) TableName() string {
	return TableNameTzSysUser
}
