// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzTranscityFree = "tz_transcity_free"

// TzTranscityFree mapped from table <tz_transcity_free>
type TzTranscityFree struct {
	TranscityFreeID int64  `gorm:"column:transcity_free_id;type:bigint(20);primaryKey;autoIncrement:true;comment:指定条件包邮城市项id" json:"transcity_free_id"` // 指定条件包邮城市项id
	TransfeeFreeID  *int64 `gorm:"column:transfee_free_id;type:bigint(20);index:transfee_free_id,priority:1;comment:指定条件包邮项id" json:"transfee_free_id"` // 指定条件包邮项id
	FreeCityID      *int64 `gorm:"column:free_city_id;type:bigint(20);index:city_id,priority:1;comment:城市id" json:"free_city_id"`                       // 城市id
}

// TableName TzTranscityFree's table name
func (*TzTranscityFree) TableName() string {
	return TableNameTzTranscityFree
}
