// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzTransfee = "tz_transfee"

// TzTransfee mapped from table <tz_transfee>
type TzTransfee struct {
	TransfeeID      int64    `gorm:"column:transfee_id;type:bigint(20);primaryKey;autoIncrement:true;comment:运费项id" json:"transfee_id"`    // 运费项id
	TransportID     *int64   `gorm:"column:transport_id;type:bigint(20);index:transport_id,priority:1;comment:运费模板id" json:"transport_id"` // 运费模板id
	ContinuousPiece *float64 `gorm:"column:continuous_piece;type:decimal(15,2);comment:续件数量" json:"continuous_piece"`                      // 续件数量
	FirstPiece      *float64 `gorm:"column:first_piece;type:decimal(15,2);comment:首件数量" json:"first_piece"`                                // 首件数量
	ContinuousFee   *float64 `gorm:"column:continuous_fee;type:decimal(15,2);comment:续件费用" json:"continuous_fee"`                          // 续件费用
	FirstFee        *float64 `gorm:"column:first_fee;type:decimal(15,2);comment:首件费用" json:"first_fee"`                                    // 首件费用
}

// TableName TzTransfee's table name
func (*TzTransfee) TableName() string {
	return TableNameTzTransfee
}
