// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTzTranscity = "tz_transcity"

// TzTranscity mapped from table <tz_transcity>
type TzTranscity struct {
	TranscityID int64  `gorm:"column:transcity_id;type:bigint(20);primaryKey;autoIncrement:true" json:"transcity_id"`
	TransfeeID  *int64 `gorm:"column:transfee_id;type:bigint(20);index:transfee_id,priority:1;comment:运费项id" json:"transfee_id"` // 运费项id
	CityID      *int64 `gorm:"column:city_id;type:bigint(20);index:city_id,priority:1;comment:城市id" json:"city_id"`              // 城市id
}

// TableName TzTranscity's table name
func (*TzTranscity) TableName() string {
	return TableNameTzTranscity
}
