// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzUserCollection = "tz_user_collection"

// TzUserCollection mapped from table <tz_user_collection>
type TzUserCollection struct {
	ID         int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:收藏表" json:"id"` // 收藏表
	ProdID     *int64     `gorm:"column:prod_id;type:bigint(20);comment:商品id" json:"prod_id"`                    // 商品id
	UserID     string     `gorm:"column:user_id;type:varchar(36);not null;comment:用户id" json:"user_id"`          // 用户id
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;comment:收藏时间" json:"create_time"`              // 收藏时间
}

// TableName TzUserCollection's table name
func (*TzUserCollection) TableName() string {
	return TableNameTzUserCollection
}
