// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzUserAddrOrder = "tz_user_addr_order"

// TzUserAddrOrder 用户订单配送地址
type TzUserAddrOrder struct {
	AddrOrderID uint64    `gorm:"column:addr_order_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"addr_order_id"` // ID
	AddrID      uint64    `gorm:"column:addr_id;type:bigint(20) unsigned;not null;comment:地址ID" json:"addr_id"`                                // 地址ID
	UserID      *string   `gorm:"column:user_id;type:varchar(36);not null;default:0;comment:用户ID" json:"user_id"`                              // 用户ID
	Receiver    *string   `gorm:"column:receiver;type:varchar(50);comment:收货人" json:"receiver"`                                                // 收货人
	ProvinceID  *int64    `gorm:"column:province_id;type:bigint(20);comment:省ID" json:"province_id"`                                           // 省ID
	Province    *string   `gorm:"column:province;type:varchar(100);comment:省" json:"province"`                                                 // 省
	AreaID      *int64    `gorm:"column:area_id;type:bigint(20);comment:区域ID" json:"area_id"`                                                  // 区域ID
	Area        *string   `gorm:"column:area;type:varchar(20);comment:区" json:"area"`                                                          // 区
	CityID      *int64    `gorm:"column:city_id;type:bigint(20);comment:城市ID" json:"city_id"`                                                  // 城市ID
	City        *string   `gorm:"column:city;type:varchar(20);comment:城市" json:"city"`                                                         // 城市
	Addr        *string   `gorm:"column:addr;type:varchar(1000);comment:地址" json:"addr"`                                                       // 地址
	PostCode    *string   `gorm:"column:post_code;type:varchar(15);comment:邮编" json:"post_code"`                                               // 邮编
	Mobile      *string   `gorm:"column:mobile;type:varchar(20);comment:手机" json:"mobile"`                                                     // 手机
	CreateTime  time.Time `gorm:"column:create_time;type:datetime;not null;comment:建立时间" json:"create_time"`                                   // 建立时间
	Version     int32     `gorm:"column:version;type:int(5);not null;comment:版本号" json:"version"`                                              // 版本号
}

// TableName TzUserAddrOrder's table name
func (*TzUserAddrOrder) TableName() string {
	return TableNameTzUserAddrOrder
}
