// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTzUser = "tz_user"

// TzUser 用户表
type TzUser struct {
	UserID        string     `gorm:"column:user_id;type:varchar(36);primaryKey;comment:ID" json:"user_id"`                                             // ID
	NickName      *string    `gorm:"column:nick_name;type:varchar(50);comment:用户昵称" json:"nick_name"`                                                  // 用户昵称
	RealName      *string    `gorm:"column:real_name;type:varchar(50);comment:真实姓名" json:"real_name"`                                                  // 真实姓名
	UserMail      *string    `gorm:"column:user_mail;type:varchar(100);uniqueIndex:ud_user_mail,priority:1;comment:用户邮箱" json:"user_mail"`             // 用户邮箱
	LoginPassword *string    `gorm:"column:login_password;type:varchar(255);comment:登录密码" json:"login_password"`                                       // 登录密码
	PayPassword   *string    `gorm:"column:pay_password;type:varchar(50);comment:支付密码" json:"pay_password"`                                            // 支付密码
	UserMobile    *string    `gorm:"column:user_mobile;type:varchar(50);uniqueIndex:ud_user_unique_mobile,priority:1;comment:手机号码" json:"user_mobile"` // 手机号码
	ModifyTime    time.Time  `gorm:"column:modify_time;type:datetime;not null;comment:修改时间" json:"modify_time"`                                        // 修改时间
	UserRegtime   time.Time  `gorm:"column:user_regtime;type:datetime;not null;comment:注册时间" json:"user_regtime"`                                      // 注册时间
	UserRegip     *string    `gorm:"column:user_regip;type:varchar(50);comment:注册IP" json:"user_regip"`                                                // 注册IP
	UserLasttime  *time.Time `gorm:"column:user_lasttime;type:datetime;comment:最后登录时间" json:"user_lasttime"`                                           // 最后登录时间
	UserLastip    *string    `gorm:"column:user_lastip;type:varchar(50);comment:最后登录IP" json:"user_lastip"`                                            // 最后登录IP
	UserMemo      *string    `gorm:"column:user_memo;type:varchar(500);comment:备注" json:"user_memo"`                                                   // 备注
	Sex           *string    `gorm:"column:sex;type:char(1);default:M;comment:M(男) or F(女)" json:"sex"`                                                // M(男) or F(女)
	BirthDate     *string    `gorm:"column:birth_date;type:char(10);comment:例如：2009-11-27" json:"birth_date"`                                          // 例如：2009-11-27
	Pic           *string    `gorm:"column:pic;type:varchar(255);comment:头像图片路径" json:"pic"`                                                           // 头像图片路径
	Status        *int32     `gorm:"column:status;type:int(1);not null;default:1;comment:状态 1 正常 0 无效" json:"status"`                                  // 状态 1 正常 0 无效
	Score         *int32     `gorm:"column:score;type:int(11);comment:用户积分" json:"score"`                                                              // 用户积分
}

// TableName TzUser's table name
func (*TzUser) TableName() string {
	return TableNameTzUser
}
