## 本地图片上传路径
local:
  path: static
mysql:
  path: localhost
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: newbee_mall_db_v2
  username: root
  password: WdRedis5188@@
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  addr: 3000
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[newbee_mall]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
